[project]
name = "week08"
version = "0.1.0"
description = ""
authors = [
    {name = "Sneha Gada",email = "your-github-email@example.com"}
]
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.142.2,<0.143.0)",
    "uvicorn (>=0.54.0,<0.55.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
